// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lufia/enttut/ent/predicate"
	"github.com/lufia/enttut/ent/transaction"
	"github.com/lufia/enttut/ent/wallet"
)

// TransactionUpdate is the builder for updating Transaction entities.
type TransactionUpdate struct {
	config
	hooks    []Hook
	mutation *TransactionMutation
}

// Where appends a list predicates to the TransactionUpdate builder.
func (tu *TransactionUpdate) Where(ps ...predicate.Transaction) *TransactionUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetPaidDate sets the "paid_date" field.
func (tu *TransactionUpdate) SetPaidDate(t time.Time) *TransactionUpdate {
	tu.mutation.SetPaidDate(t)
	return tu
}

// SetNillablePaidDate sets the "paid_date" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillablePaidDate(t *time.Time) *TransactionUpdate {
	if t != nil {
		tu.SetPaidDate(*t)
	}
	return tu
}

// SetAmount sets the "amount" field.
func (tu *TransactionUpdate) SetAmount(i int) *TransactionUpdate {
	tu.mutation.ResetAmount()
	tu.mutation.SetAmount(i)
	return tu
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableAmount(i *int) *TransactionUpdate {
	if i != nil {
		tu.SetAmount(*i)
	}
	return tu
}

// AddAmount adds i to the "amount" field.
func (tu *TransactionUpdate) AddAmount(i int) *TransactionUpdate {
	tu.mutation.AddAmount(i)
	return tu
}

// SetMemo sets the "memo" field.
func (tu *TransactionUpdate) SetMemo(s string) *TransactionUpdate {
	tu.mutation.SetMemo(s)
	return tu
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableMemo(s *string) *TransactionUpdate {
	if s != nil {
		tu.SetMemo(*s)
	}
	return tu
}

// SetWalletID sets the "wallet" edge to the Wallet entity by ID.
func (tu *TransactionUpdate) SetWalletID(id int) *TransactionUpdate {
	tu.mutation.SetWalletID(id)
	return tu
}

// SetNillableWalletID sets the "wallet" edge to the Wallet entity by ID if the given value is not nil.
func (tu *TransactionUpdate) SetNillableWalletID(id *int) *TransactionUpdate {
	if id != nil {
		tu = tu.SetWalletID(*id)
	}
	return tu
}

// SetWallet sets the "wallet" edge to the Wallet entity.
func (tu *TransactionUpdate) SetWallet(w *Wallet) *TransactionUpdate {
	return tu.SetWalletID(w.ID)
}

// Mutation returns the TransactionMutation object of the builder.
func (tu *TransactionUpdate) Mutation() *TransactionMutation {
	return tu.mutation
}

// ClearWallet clears the "wallet" edge to the Wallet entity.
func (tu *TransactionUpdate) ClearWallet() *TransactionUpdate {
	tu.mutation.ClearWallet()
	return tu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TransactionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TransactionUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TransactionUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TransactionUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tu *TransactionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(transaction.Table, transaction.Columns, sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.PaidDate(); ok {
		_spec.SetField(transaction.FieldPaidDate, field.TypeTime, value)
	}
	if value, ok := tu.mutation.Amount(); ok {
		_spec.SetField(transaction.FieldAmount, field.TypeInt, value)
	}
	if value, ok := tu.mutation.AddedAmount(); ok {
		_spec.AddField(transaction.FieldAmount, field.TypeInt, value)
	}
	if value, ok := tu.mutation.Memo(); ok {
		_spec.SetField(transaction.FieldMemo, field.TypeString, value)
	}
	if tu.mutation.WalletCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.WalletTable,
			Columns: []string{transaction.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.WalletIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.WalletTable,
			Columns: []string{transaction.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TransactionUpdateOne is the builder for updating a single Transaction entity.
type TransactionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TransactionMutation
}

// SetPaidDate sets the "paid_date" field.
func (tuo *TransactionUpdateOne) SetPaidDate(t time.Time) *TransactionUpdateOne {
	tuo.mutation.SetPaidDate(t)
	return tuo
}

// SetNillablePaidDate sets the "paid_date" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillablePaidDate(t *time.Time) *TransactionUpdateOne {
	if t != nil {
		tuo.SetPaidDate(*t)
	}
	return tuo
}

// SetAmount sets the "amount" field.
func (tuo *TransactionUpdateOne) SetAmount(i int) *TransactionUpdateOne {
	tuo.mutation.ResetAmount()
	tuo.mutation.SetAmount(i)
	return tuo
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableAmount(i *int) *TransactionUpdateOne {
	if i != nil {
		tuo.SetAmount(*i)
	}
	return tuo
}

// AddAmount adds i to the "amount" field.
func (tuo *TransactionUpdateOne) AddAmount(i int) *TransactionUpdateOne {
	tuo.mutation.AddAmount(i)
	return tuo
}

// SetMemo sets the "memo" field.
func (tuo *TransactionUpdateOne) SetMemo(s string) *TransactionUpdateOne {
	tuo.mutation.SetMemo(s)
	return tuo
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableMemo(s *string) *TransactionUpdateOne {
	if s != nil {
		tuo.SetMemo(*s)
	}
	return tuo
}

// SetWalletID sets the "wallet" edge to the Wallet entity by ID.
func (tuo *TransactionUpdateOne) SetWalletID(id int) *TransactionUpdateOne {
	tuo.mutation.SetWalletID(id)
	return tuo
}

// SetNillableWalletID sets the "wallet" edge to the Wallet entity by ID if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableWalletID(id *int) *TransactionUpdateOne {
	if id != nil {
		tuo = tuo.SetWalletID(*id)
	}
	return tuo
}

// SetWallet sets the "wallet" edge to the Wallet entity.
func (tuo *TransactionUpdateOne) SetWallet(w *Wallet) *TransactionUpdateOne {
	return tuo.SetWalletID(w.ID)
}

// Mutation returns the TransactionMutation object of the builder.
func (tuo *TransactionUpdateOne) Mutation() *TransactionMutation {
	return tuo.mutation
}

// ClearWallet clears the "wallet" edge to the Wallet entity.
func (tuo *TransactionUpdateOne) ClearWallet() *TransactionUpdateOne {
	tuo.mutation.ClearWallet()
	return tuo
}

// Where appends a list predicates to the TransactionUpdate builder.
func (tuo *TransactionUpdateOne) Where(ps ...predicate.Transaction) *TransactionUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TransactionUpdateOne) Select(field string, fields ...string) *TransactionUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Transaction entity.
func (tuo *TransactionUpdateOne) Save(ctx context.Context) (*Transaction, error) {
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TransactionUpdateOne) SaveX(ctx context.Context) *Transaction {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TransactionUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TransactionUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tuo *TransactionUpdateOne) sqlSave(ctx context.Context) (_node *Transaction, err error) {
	_spec := sqlgraph.NewUpdateSpec(transaction.Table, transaction.Columns, sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Transaction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transaction.FieldID)
		for _, f := range fields {
			if !transaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != transaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.PaidDate(); ok {
		_spec.SetField(transaction.FieldPaidDate, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.Amount(); ok {
		_spec.SetField(transaction.FieldAmount, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.AddedAmount(); ok {
		_spec.AddField(transaction.FieldAmount, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.Memo(); ok {
		_spec.SetField(transaction.FieldMemo, field.TypeString, value)
	}
	if tuo.mutation.WalletCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.WalletTable,
			Columns: []string{transaction.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.WalletIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.WalletTable,
			Columns: []string{transaction.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Transaction{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
